### ISSUE TITLE
There seem to be some errors in Figure 2 that need to be corrected

### ISSUE THREAD

**Issue by aisi746467512** [jingge326/FlexTSF#1]
The direction of the time coordinate system in the IVP solver is reversed

**Comment by jingge326** [comment]
Thank you for your feedback. The directions of the arrows should be different. Please refer to Algorithm 1 (Part 1/Part 2) line 2.

**Comment by aisi746467512** [comment]
I know what you mean. In Part 1 and Part 2, the operation direction of IVP Solver is opposite, I just suggest that the time coordinate system should still be the same.
